version: '3.8'

services:
  # API Monitor Application
  api-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-monitor
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://monitor:secret@postgres:5432/api_monitor
      - CONFIG_PATH=/app/config/config.yaml
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - monitor-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: api-monitor-db
    environment:
      POSTGRES_DB: api_monitor
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - monitor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  monitor-network:
    driver: bridge